from typing import Protocol


class ObjectStorage(Protocol):
    def create_upload_target(self, key: str, mime_type: str) -> str: ...
    def delete(self, key: str) -> None: ...
    def public_url(self, key: str) -> str | None: ...
