import type { Metadata } from "next";
import Link from "next/link";
import SchemaOrg from "@/components/SchemaOrg";
import DigitalProductCallout from "@/components/digital-products/DigitalProductCallout";
import PricingCalculator from "./PricingCalculator";

export const metadata: Metadata = { title: "Pricing Calculator", description: "Calculate a selling price from your cost and desired profit margin in INR.", alternates: { canonical: "/tools/pricing-calculator" }, openGraph: { title: "Pricing Calculator | LeTrusto", description: "Calculate a selling price from your cost and desired profit margin in INR.", url: "/tools/pricing-calculator", siteName: "LeTrusto", type: "website" } };

export default function PricingCalculatorPage() {
  return <main className="mx-auto max-w-7xl px-4 py-12 md:px-6 md:py-20"><SchemaOrg type="WebPage" data={{ name: "Pricing Calculator", url: "/tools/pricing-calculator", description: "Calculate a selling price from cost and desired profit margin." }} /><div className="max-w-3xl"><Link href="/tools" className="text-sm font-semibold text-[var(--lt-primary)] hover:text-[var(--lt-accent)]">&larr; All tools</Link><p className="lt-eyebrow mt-8">Free calculator</p><h1 className="lt-heading-1 mt-3">Pricing Calculator</h1><p className="mt-5 text-lg leading-relaxed text-[var(--text-secondary)]">Work backwards from a target profit margin to find a selling price that covers your cost.</p></div><div className="mt-10 md:mt-14"><PricingCalculator /></div><section className="mt-16 grid gap-10 border-t border-[var(--border)] pt-12 md:grid-cols-2"><div><h2 className="lt-heading-2">Margin vs markup</h2><p className="lt-body mt-4">Margin is profit as a percentage of the selling price. Markup is profit as a percentage of the cost. This calculator uses your desired margin to calculate the selling price.</p></div><div className="border border-[var(--border)] bg-[var(--surface-soft)] p-6"><h2 className="lt-heading-2">Formula</h2><p className="mt-5 font-mono text-sm text-[var(--text-primary)]">Selling Price = Cost / (1 - Margin / 100)</p><p className="mt-4 text-xs text-[var(--text-muted)]">All calculations happen locally in your browser.</p></div></section><DigitalProductCallout /></main>;
}
