import { authenticatedApiRequest } from "@/services/api";

export type AdminSeller = { id: string; display_name: string; seller_type: string; phone: string; email: string | null; whatsapp_available: boolean; verification_status: string; property_count: number | null; created_at: string | null };
export type AdminEnquiry = { id: string; property_id: string; property_title: string; seller_name: string; buyer_name: string; buyer_phone: string; buyer_email: string | null; whatsapp_available: boolean; budget_amount: number | string | null; buying_timeline: string | null; message: string | null; preferred_contact_method: string; source: string; status: string; consent_to_share: boolean; created_at: string };
export type AdminProperty = { id: string; slug: string; title: string; description: string; property_type: string; price_amount: number | string; currency: string; built_up_area_sqft: number | string | null; carpet_area_sqft: number | string | null; plot_area_sqft: number | string | null; bhk: number | null; floor_number: number | null; total_floors: number | null; property_age_years: number | null; facing: string | null; parking_details: string | null; maintenance_amount: number | string | null; possession_status: string | null; road_width_ft: number | string | null; plot_dimensions: string | null; corner_site: boolean | null; approval_information: string | null; amenities: Record<string, boolean> | null; address_line: string | null; address_visibility: string; latitude: number | string | null; longitude: number | string | null; status: string; submitted_at: string | null; published_at: string | null; created_at: string; updated_at: string; location: { name: string; city_name: string }; media: { id: string; media_type: string; public_url: string | null; sort_order: number; is_cover: boolean; caption: string | null; status: string }[]; seller: AdminSeller; verification: { verification_status: string; verification_method: string | null; notes: string | null; verified_by: string | null; verified_at: string | null; expires_at: string | null } | null; reviews: { id: string; decision: string; notes: string | null; reviewer_id: string; reviewer_name: string | null; created_at: string }[]; audit: { id: string; action: string; metadata: Record<string, unknown> | null; actor_user_id: string | null; created_at: string }[] };
export type AdminDashboard = { awaiting_review: number; changes_requested: number; live_properties: number; suspended_properties: number; recent_enquiries: AdminEnquiry[] };
export type SocialPost = { id: string; platform: string; post_type: string; headline: string | null; body: string; cta: string | null; content: string | null; status: string };
export type AdminCampaign = { id: string; property_id: string; property_title: string; property_slug: string; campaign_title: string; campaign_key: string; campaign_description: string | null; source: string; medium: string; content: string | null; status: string; public_path: string; social_posts: SocialPost[]; created_at: string; updated_at: string };

export function getAdminDashboard(token: string) { return authenticatedApiRequest<AdminDashboard>(token, "/admin/dashboard"); }
export function listAdminProperties(token: string) { return authenticatedApiRequest<AdminProperty[]>(token, "/admin/properties"); }
export function getAdminProperty(token: string, id: string) { return authenticatedApiRequest<AdminProperty>(token, `/admin/properties/${id}`); }
export function listAdminEnquiries(token: string) { return authenticatedApiRequest<AdminEnquiry[]>(token, "/admin/enquiries"); }
export function listAdminSellers(token: string) { return authenticatedApiRequest<AdminSeller[]>(token, "/admin/sellers"); }
export function reviewAdminProperty(token: string, id: string, decision: "APPROVED" | "CHANGES_REQUESTED" | "REJECTED", notes?: string) { return authenticatedApiRequest<{ id: string; status: string }>(token, `/admin/properties/${id}/review`, { method: "POST", body: JSON.stringify({ decision, notes }) }); }
export function publishAdminProperty(token: string, id: string) { return authenticatedApiRequest<{ id: string; status: string }>(token, `/admin/properties/${id}/publish`, { method: "POST" }); }
export function updateAdminVerification(token: string, id: string, verification_status: string, notes?: string) { return authenticatedApiRequest<{ id: string; status: string }>(token, `/admin/properties/${id}/verification`, { method: "PATCH", body: JSON.stringify({ verification_status, notes }) }); }
export function listAdminCampaigns(token: string, propertyId: string) { return authenticatedApiRequest<AdminCampaign[]>(token, `/admin/properties/${propertyId}/campaigns`); }
export function createAdminCampaign(token: string, propertyId: string, payload: Record<string, unknown>) { return authenticatedApiRequest<AdminCampaign>(token, `/admin/properties/${propertyId}/campaigns`, { method: "POST", body: JSON.stringify(payload) }); }
export function updateAdminCampaign(token: string, id: string, payload: Record<string, unknown>) { return authenticatedApiRequest<AdminCampaign>(token, `/admin/campaigns/${id}`, { method: "PATCH", body: JSON.stringify(payload) }); }
