"use client";

import { useMemo, useState } from "react";
import { Plus, RotateCcw, Trash2 } from "lucide-react";
import { calculateExpenses, validateExpense, type ExpenseCalculation, type ExpenseEntry } from "@/lib/expenseCalculator";

const CATEGORIES = ["Rent", "Salaries", "Marketing", "Software", "Utilities", "Travel", "Shipping", "Office", "Other"];
const currencyFormatter = new Intl.NumberFormat("en-IN", { maximumFractionDigits: 2 });
function currency(value: number) { return Number.isFinite(value) ? `₹${currencyFormatter.format(value)}` : "Not available"; }
function newExpense(): ExpenseEntry { return { id: `${Date.now()}-${Math.random()}`, name: "", category: "Software", amount: 0 }; }

export default function ExpenseCalculator() {
  const [entries, setEntries] = useState<ExpenseEntry[]>([newExpense()]);
  const errors = entries.map(validateExpense).filter(Boolean) as string[];
  const calculation = useMemo<ExpenseCalculation | null>(() => { if (errors.length > 0) return null; try { return calculateExpenses(entries); } catch { return null; } }, [entries, errors.length]);
  function updateEntry(id: string, field: keyof ExpenseEntry, value: string) { setEntries((current) => current.map((entry) => entry.id === id ? { ...entry, [field]: field === "amount" ? Number(value) : value } : entry)); }
  function reset() { setEntries([newExpense()]); }

  return <div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_minmax(340px,0.85fr)]"><section className="lt-card"><div className="flex items-start justify-between gap-4"><div><p className="lt-eyebrow">Entries</p><h2 className="lt-heading-2 mt-2">Track your expenses</h2></div><button type="button" onClick={reset} className="lt-btn lt-btn-sm lt-btn-ghost shrink-0" aria-label="Reset expense calculator"><RotateCcw size={15} /> Reset</button></div><div className="mt-8 space-y-4">{entries.map((entry, index) => { const error = validateExpense(entry); return <div key={entry.id} className="border border-[var(--border)] bg-[var(--surface-soft)] p-4"><div className="grid gap-4 sm:grid-cols-[minmax(0,1fr)_150px_130px_40px] sm:items-end"><div><label htmlFor={`expense-name-${entry.id}`} className="lt-label mb-2 block">Expense {index + 1}</label><input id={`expense-name-${entry.id}`} className="lt-input" value={entry.name} onChange={(event) => updateEntry(entry.id, "name", event.target.value)} placeholder="Expense name" /></div><div><label htmlFor={`expense-category-${entry.id}`} className="lt-label mb-2 block">Category</label><select id={`expense-category-${entry.id}`} className="lt-select w-full" value={entry.category} onChange={(event) => updateEntry(entry.id, "category", event.target.value)}>{CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select></div><div><label htmlFor={`expense-amount-${entry.id}`} className="lt-label mb-2 block">Amount (₹)</label><input id={`expense-amount-${entry.id}`} className="lt-input" type="number" min="0" step="any" value={entry.amount} onChange={(event) => updateEntry(entry.id, "amount", event.target.value)} /></div><button type="button" onClick={() => setEntries((current) => current.filter((currentEntry) => currentEntry.id !== entry.id))} className="flex h-10 w-10 items-center justify-center text-[var(--text-secondary)] hover:text-[var(--lt-accent-dark)]" aria-label={`Remove expense ${index + 1}`}><Trash2 size={18} /></button></div>{error && <p className="mt-2 text-xs font-semibold text-[var(--lt-accent-dark)]" role="alert">{error}</p>}</div>; })}</div><button type="button" onClick={() => setEntries((current) => [...current, newExpense()])} className="lt-btn lt-btn-sm lt-btn-secondary mt-5"><Plus size={16} /> Add expense</button></section><section className="lt-card" aria-live="polite" aria-label="Expense calculator results"><p className="lt-eyebrow">Summary</p>{calculation ? <Results calculation={calculation} /> : <div className="flex min-h-64 items-center justify-center py-10 text-center"><p className="max-w-xs text-sm leading-relaxed text-[var(--text-secondary)]">Add a named expense to see your total and category breakdown.</p></div>}</section></div>;
}

function Results({ calculation }: { calculation: ExpenseCalculation }) { const categories = Object.entries(calculation.categoryTotals); return <div className="mt-6"><div className="border-b border-[var(--border)] pb-6"><p className="text-sm font-semibold text-[var(--text-secondary)]">Total expenses</p><p className="mt-2 break-words text-4xl font-black text-[var(--lt-primary)]">{currency(calculation.total)}</p><p className="mt-2 text-sm text-[var(--text-secondary)]">{calculation.count} {calculation.count === 1 ? "expense" : "expenses"}</p></div><div className="mt-6"><h3 className="text-sm font-bold text-[var(--text-primary)]">By category</h3><dl className="mt-3 space-y-3">{categories.map(([category, total]) => <div key={category} className="flex justify-between gap-4 border-b border-[var(--border)] pb-2 text-sm"><dt className="text-[var(--text-secondary)]">{category}</dt><dd className="font-semibold text-[var(--text-primary)]">{currency(total)}</dd></div>)}</dl></div></div>; }
