import type { Metadata } from "next";
import Link from "next/link";
import SchemaOrg from "@/components/SchemaOrg";
import BreakEvenCalculator from "./BreakEvenCalculator";

export const metadata: Metadata = { title: "Break-Even Calculator", description: "Calculate the units and revenue needed to cover fixed and variable business costs.", alternates: { canonical: "/tools/break-even-calculator" }, openGraph: { title: "Break-Even Calculator | LeTrusto", description: "Calculate the units and revenue needed to cover fixed and variable business costs.", url: "/tools/break-even-calculator", siteName: "LeTrusto", type: "website" } };

export default function BreakEvenCalculatorPage() {
  return <main className="mx-auto max-w-7xl px-4 py-12 md:px-6 md:py-20"><SchemaOrg type="WebPage" data={{ name: "Break-Even Calculator", url: "/tools/break-even-calculator", description: "Calculate break-even units, revenue, and contribution per unit." }} /><div className="max-w-3xl"><Link href="/tools" className="text-sm font-semibold text-[var(--lt-primary)] hover:text-[var(--lt-accent)]">&larr; All tools</Link><p className="lt-eyebrow mt-8">Free calculator</p><h1 className="lt-heading-1 mt-3">Break-Even Calculator</h1><p className="mt-5 text-lg leading-relaxed text-[var(--text-secondary)]">Estimate how many units you need to sell to cover your fixed and variable costs.</p></div><div className="mt-10 md:mt-14"><BreakEvenCalculator /></div><section className="mt-16 grid gap-10 border-t border-[var(--border)] pt-12 md:grid-cols-2"><div><h2 className="lt-heading-2">How break-even works</h2><p className="lt-body mt-4">Each unit contributes its selling price minus its variable cost toward fixed costs. If selling price is equal to or below variable cost, unit sales cannot cover fixed costs under these assumptions.</p></div><div className="border border-[var(--border)] bg-[var(--surface-soft)] p-6"><h2 className="lt-heading-2">Formula</h2><p className="mt-5 font-mono text-sm text-[var(--text-primary)]">Break-Even Quantity = Fixed Costs / (Selling Price - Variable Cost)</p><p className="mt-4 text-xs text-[var(--text-muted)]">Unit quantity is rounded up for planning; revenue uses the exact calculated quantity.</p></div></section></main>;
}
