"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Lock, Plus } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { API_BASE_URL } from "@/services/api";

type CAC={spend:number;attributed_orders:number;attributed_cac:number|null;blended_cac:number|null;target_cac:number;actual_cac_status:string;rows:{channel:string;campaign:string|null;spend:number;attributed_orders:number;attributed_cac:number|null;roas:number|null;cac_status:string}[]};
type Spend={id:string;spend_date:string;channel:string;campaign:string|null;spend_amount:number;currency:string};
export default function MarketingView(){const {accessToken,isLoading,isAuthenticated,isAdmin}=useAuth();const [cac,setCac]=useState<CAC|null>(null);const [spend,setSpend]=useState<Spend[]>([]);const [error,setError]=useState("");const [form,setForm]=useState({spend_date:new Date().toISOString().slice(0,10),channel:"META",campaign:"",spend_amount:"",currency:"INR",notes:""});
useEffect(()=>{if(!accessToken||!isAdmin)return;void Promise.all([fetch(`${API_BASE_URL}/api/v1/admin/marketing/cac`,{headers:{Authorization:`Bearer ${accessToken}`}}),fetch(`${API_BASE_URL}/api/v1/admin/marketing/spend`,{headers:{Authorization:`Bearer ${accessToken}`}})]).then(async([a,b])=>{if(!a.ok||!b.ok)throw new Error("Unable to load marketing data");setCac(await a.json());setSpend(await b.json());}).catch(e=>setError(e.message));},[accessToken,isAdmin]);
async function addSpend(e:React.FormEvent){e.preventDefault();if(!accessToken)return;const r=await fetch(`${API_BASE_URL}/api/v1/admin/marketing/spend`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${accessToken}`},body:JSON.stringify({...form,spend_amount:form.spend_amount})});if(!r.ok){setError("Unable to save marketing spend");return;}setForm({...form,spend_amount:"",campaign:"",notes:""});const row=await r.json();setSpend([row,...spend]);}
if(isLoading)return <main className="mx-auto max-w-5xl px-5 py-16 text-center">Loading marketing...</main>;if(!isAuthenticated||!isAdmin)return <main className="mx-auto max-w-3xl px-5 py-16 text-center"><Lock className="mx-auto"/><h1 className="lt-heading-2 mt-4">Admin access required</h1><Link href="/login" className="lt-btn lt-btn-primary mt-6 inline-flex">Sign In</Link></main>;
return <main className="mx-auto max-w-5xl px-5 py-8 md:py-12"><p className="lt-label">Business operations</p><h1 className="lt-heading-1 mt-2">Marketing</h1><p className="mt-2 text-sm text-[var(--text-secondary)]">Actual CAC uses explicit attribution only. Blended CAC is a separate company-level metric.</p>{error&&<p role="alert" className="mt-5 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<section className="mt-8 grid grid-cols-2 gap-4 md:grid-cols-4"><Card label="Spend" value={cac?`₹${cac.spend.toLocaleString("en-IN")}` : "Not available"}/><Card label="Target CAC" value={cac?`₹${cac.target_cac}`:"₹150"}/><Card label="Actual attributed CAC" value={cac?.attributed_cac?`₹${cac.attributed_cac.toFixed(2)}`:"Not configured"}/><Card label="Blended CAC" value={cac?.blended_cac?`₹${cac.blended_cac.toFixed(2)}`:"Not available"}/></section><section className="lt-card mt-8"><h2 className="text-lg font-bold">Record marketing spend</h2><form onSubmit={addSpend} className="mt-4 grid gap-3 md:grid-cols-5"><input type="date" className="lt-input" value={form.spend_date} onChange={e=>setForm({...form,spend_date:e.target.value})}/><input className="lt-input" placeholder="Channel" value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})}/><input className="lt-input" placeholder="Campaign (optional)" value={form.campaign} onChange={e=>setForm({...form,campaign:e.target.value})}/><input className="lt-input" type="number" min="0" step="0.01" required placeholder="Spend INR" value={form.spend_amount} onChange={e=>setForm({...form,spend_amount:e.target.value})}/><button className="lt-btn lt-btn-primary"><Plus size={15}/> Add spend</button></form></section><div className="mt-8 grid gap-8 md:grid-cols-2"><section className="lt-card"><h2 className="text-lg font-bold">By channel</h2><div className="mt-4 space-y-3">{cac?.rows.map(row=><div key={`${row.channel}-${row.campaign ?? ""}`} className="border-t pt-3 text-sm"><div className="flex justify-between"><b>{row.channel}{row.campaign?` · ${row.campaign}`:""}</b><span>₹{row.spend}</span></div><p className="mt-1 text-xs text-[var(--text-secondary)]">Attributed orders: {row.attributed_orders} · CAC: {row.attributed_cac?`₹${row.attributed_cac.toFixed(2)}`:"Not attributed"} · ROAS: {row.roas?`${row.roas.toFixed(2)}x`:"Not available"}</p></div>)}</div></section><section className="lt-card"><h2 className="text-lg font-bold">Spend records</h2><div className="mt-4 space-y-3">{spend.map(row=><div key={row.id} className="border-t pt-3 text-sm"><div className="flex justify-between"><b>{row.channel}</b><span>₹{row.spend_amount}</span></div><p className="text-xs text-[var(--text-secondary)]">{row.spend_date}{row.campaign?` · ${row.campaign}`:""}</p></div>)}</div>{spend.length===0&&<p className="mt-4 text-sm text-[var(--text-muted)]">No marketing spend recorded.</p>}</section></div></main>}
function Card({label,value}:{label:string;value:string}){return <div className="lt-card"><p className="lt-label">{label}</p><p className="mt-2 text-xl font-bold">{value}</p></div>}
