import Link from "next/link";
import { ArrowRight, BarChart3, Check, FileText, LayoutTemplate, Sparkles } from "lucide-react";
import { formatDigitalProductPrice, getPublishedDigitalProducts } from "@/lib/digitalProducts";

const serviceAreas = ["Websites", "Ecommerce", "Automation", "Dashboards"];

export default function Hero() {
  const products = getPublishedDigitalProducts();
  return (
    <>
      <section className="relative overflow-hidden bg-[#26113c] text-white">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_15%,rgba(236,72,153,0.34),transparent_30%),radial-gradient(circle_at_15%_80%,rgba(139,92,246,0.36),transparent_34%)]" />
        <div className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 py-16 md:px-8 md:py-24 lg:grid-cols-[1.05fr_0.95fr] lg:py-28">
          <div className="max-w-2xl">
            <p className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-pink-300"><Sparkles size={15} /> Practical digital solutions</p>
            <h1 className="mt-6 text-5xl font-black leading-[0.98] tracking-[-0.04em] sm:text-6xl lg:text-7xl">Make the next move with clarity.</h1>
            <p className="mt-6 max-w-xl text-lg leading-8 text-purple-100">Tools, ready-to-use workbooks and thoughtful digital services for Indian businesses, freelancers and creators.</p>
            <div className="mt-9 flex flex-wrap gap-3"><Link href="#products" className="lt-btn lt-btn-lg bg-pink-500 text-white hover:bg-pink-400">Shop digital products <ArrowRight size={17} /></Link><Link href="/tools" className="lt-btn lt-btn-lg border border-white/30 text-white hover:bg-white/10">Try free tools</Link></div>
            <div className="mt-10 flex flex-wrap gap-x-6 gap-y-2 text-sm text-purple-200"><span>Instant, protected delivery</span><span>No bloated software</span><span>Built for real work</span></div>
          </div>
          <div className="relative mx-auto w-full max-w-[510px] lg:justify-self-end"><div className="absolute -right-3 top-4 h-28 w-28 rounded-full border border-pink-300/30 motion-safe:animate-pulse" /><div className="relative rotate-1 rounded-[1.5rem] border border-white/15 bg-white/10 p-3 shadow-2xl backdrop-blur-xl motion-safe:animate-[float_7s_ease-in-out_infinite]"><div className="rounded-[1rem] bg-[#faf8ff] p-5 text-[#321347]"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-[0.16em] text-[#8b5cf6]">Monthly command centre</span><BarChart3 size={20} className="text-pink-500" /></div><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#f0e9ff] p-4"><p className="text-xs text-[#765a87]">Revenue</p><p className="mt-2 text-2xl font-black">₹1.24L</p><p className="mt-1 text-xs font-semibold text-emerald-600">+18.4%</p></div><div className="rounded-xl bg-[#ffe8f2] p-4"><p className="text-xs text-[#765a87]">Margin</p><p className="mt-2 text-2xl font-black">32.6%</p><p className="mt-1 text-xs font-semibold text-pink-600">On target</p></div></div><div className="mt-4 rounded-xl border border-[#e6daf1] bg-white p-4"><div className="flex items-end gap-2" aria-hidden="true">{[38, 54, 45, 68, 62, 80, 74].map((height, index) => <span key={index} className="flex-1 rounded-t-md bg-gradient-to-t from-[#6b21a8] to-[#ec4899]" style={{ height: `${height}px` }} />)}</div><div className="mt-3 flex justify-between text-[10px] font-semibold text-[#9b7fb0]"><span>Mon</span><span>Today</span><span>Next move</span></div></div><div className="mt-4 flex items-center gap-3 rounded-xl bg-[#321347] p-3 text-white"><Check size={17} className="text-pink-300" /><span className="text-xs font-semibold">A clearer decision is ready.</span></div></div></div></div>
        </div>
      </section>
      <section id="products" className="bg-[var(--surface-soft)] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="lt-eyebrow">Ready when you are</p><h2 className="lt-heading-2 mt-3 max-w-xl">Workbooks for the work behind the work.</h2><p className="mt-4 max-w-2xl text-base leading-7 text-[var(--text-secondary)]">Open a practical system, add your own numbers and spend less time rebuilding the same decisions from scratch.</p></div><Link href="/digital-products" className="lt-btn lt-btn-md lt-btn-secondary">View all products <ArrowRight size={16} /></Link></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{products.map((product, index) => <article key={product.slug} className="group flex flex-col overflow-hidden rounded-[1.25rem] border border-[var(--border)] bg-[var(--surface)] shadow-[0_12px_35px_rgba(60,35,100,0.08)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_20px_45px_rgba(60,35,100,0.14)]"><div className={`relative h-44 overflow-hidden p-6 ${index === 1 ? "bg-[#321347]" : index === 2 ? "bg-[#dcecf0]" : "bg-[#eee3ff]"}`}><div className="absolute -right-8 -top-10 h-36 w-36 rounded-full bg-pink-400/30 blur-2xl" /><div className="relative flex h-full flex-col justify-between"><div className="flex items-center justify-between"><span className={`rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-widest ${index === 1 ? "bg-white/15 text-pink-200" : "bg-white/70 text-[#6b21a8]"}`}>{product.previewLabel}</span>{index === 0 ? <BarChart3 size={25} className="text-pink-500" /> : index === 1 ? <LayoutTemplate size={25} className="text-pink-300" /> : <FileText size={25} className="text-[#6b21a8]" />}</div><div className={`flex items-end gap-1 ${index === 1 ? "text-white" : "text-[#321347]"}`}><span className="text-4xl font-black">₹{product.price}</span><span className="pb-1 text-xs opacity-70">one-time</span></div></div></div><div className="flex flex-1 flex-col p-6"><h3 className="text-xl font-black text-[var(--text-primary)]">{product.name}</h3><p className="mt-3 text-sm leading-6 text-[var(--text-secondary)]">{product.valueProposition}</p><div className="mt-5 space-y-2 text-sm text-[var(--text-secondary)]"><p className="flex gap-2"><Check size={16} className="mt-0.5 shrink-0 text-pink-500" />Editable CSV workbook</p><p className="flex gap-2"><Check size={16} className="mt-0.5 shrink-0 text-pink-500" />Protected download after purchase</p></div><Link href={`/digital-products/${product.slug}`} className="lt-btn lt-btn-md lt-btn-primary mt-7 w-full" aria-label={`Buy ${product.name} now`}>BUY NOW · {formatDigitalProductPrice(product)} <ArrowRight size={16} /></Link></div></article>)}</div></div></section>
      <section className="bg-[var(--background)] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p className="lt-eyebrow">Need a tailored next step?</p><h2 className="lt-heading-2 mt-3">A digital partner for the messy middle.</h2><p className="mt-4 text-base leading-7 text-[var(--text-secondary)]">From a focused landing page to a workflow that finally connects, we scope practical digital work around what needs to happen next.</p><Link href="/services" className="lt-btn lt-btn-lg lt-btn-primary mt-7">Explore services <ArrowRight size={17} /></Link></div><div className="grid gap-3 sm:grid-cols-2">{serviceAreas.map((area, index) => <Link key={area} href="/services" className="group flex min-h-28 items-end justify-between rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 transition hover:border-pink-300 hover:bg-white"><span className="text-lg font-black text-[var(--text-primary)]">{area}</span><span className="text-3xl font-black text-pink-300 transition group-hover:text-pink-500">0{index + 1}</span></Link>)}</div></div></section>
    </>
  );
}
