export const productImagesById: Partial<Record<string, string[]>> = {
  "iphone16pro": ["/images/products/iphone16pro-1.svg"],
  "galaxy-s25": ["/images/products/galaxy-s25-1.png"],
  "nothing-phone-2a": ["/images/products/nothing-phone-2a-1.jpg"],
  "oneplus-nord-4": ["/images/products/oneplus-nord-4-1.jpg"],
  "macbook-air-m4": ["/images/products/macbook-air-m4.png"],
  "sony-wh-1000xm6": ["/images/products/sony-wh1000xm6.png"],
  "bose-qc-ultra": ["/images/products/bose-qc-ultra-1.jpg"],
  "sony-bravia-7-55": ["/images/products/sony-bravia-7-55-1.jpg"],
  "tcl-c755-55": ["/images/products/tcl-c755-55-1.png"],
  "ifb-senator-mxn-8012": ["/images/products/ifb-senator-mxn-8012-1.jpg"],
  "whirlpool-stainwash-pro-9kg": ["/images/products/whirlpool-stainwash-pro-9kg-1.jpg"],
  "lenovo-legion-go": ["/images/products/lenovo-legion-go-1.jpg"],
  "nintendo-switch-oled": ["/images/products/nintendo-switch-oled-1.png"],
  "ipad-air-m2": ["/images/products/ipad-air-m2-1.jpg"],
  "samsung-galaxy-tab-s10": ["/images/products/samsung-galaxy-tab-s10-1.png"],
  "sony-a7-iv": ["/images/products/sony-a7-iv-1.jpg"],
};

export const productsMissingImages: string[] = [
  "motorola-edge-50-pro",
  "asus-zenbook-14-oled",
  "lenovo-thinkpad-x1-carbon",
  "dell-xps-13",
  "hp-spectre-x360-14",
  "airpods-max",
  "sennheiser-momentum-4",
  "jbl-tour-one-m2",
  "apple-watch-series-10",
  "samsung-galaxy-watch-7",
  "garmin-venu-3",
  "oneplus-watch-2",
  "amazfit-balance",
  "lg-oled-evo-c4-55",
  "samsung-qn90d-55",
  "hisense-u7n-55",
  "samsung-bespoke-415l",
  "lg-instaview-655l",
  "whirlpool-proton-340l",
  "haier-bottom-mount-325l",
  "godrej-edge-pro-310l",
  "lg-front-load-9kg",
  "samsung-ecobubble-8kg",
  "bosch-serie-6-8kg",
  "ps5-slim",
  "xbox-series-x",
  "asus-rog-ally-x",
  "oneplus-pad-2",
  "xiaomi-pad-6s-pro",
  "lenovo-tab-p12",
  "canon-r6-mark-ii",
  "nikon-z6-iii",
  "fujifilm-x-s20",
  "gopro-hero13-black",
];
