import type { Metadata } from "next";
import Link from "next/link";
import DigitalProductCallout from "@/components/digital-products/DigitalProductCallout";
import ServiceCallout from "@/components/services/ServiceCallout";
import FreelancerRateCalculator from "./FreelancerRateCalculator";

export const metadata: Metadata = { title: "Freelancer Rate Calculator", description: "Estimate an hourly and daily freelance rate from your income target, expenses, billable hours and unpaid-time buffer.", alternates: { canonical: "/tools/freelancer-rate-calculator" } };

export default function FreelancerRateCalculatorPage() { return <main className="mx-auto max-w-7xl px-4 py-12 md:px-6 md:py-20"><div className="max-w-3xl"><Link href="/tools" className="text-sm font-semibold text-[var(--lt-primary)]">&larr; All tools</Link><p className="lt-eyebrow mt-8">Free calculator</p><h1 className="lt-heading-1 mt-3">Freelancer Rate Calculator</h1><p className="mt-5 text-lg leading-relaxed text-[var(--text-secondary)]">Estimate a sustainable hourly and daily rate from your monthly target, costs and realistic billable time.</p></div><div className="mt-10 md:mt-14"><FreelancerRateCalculator /></div><section className="mt-16 grid gap-10 border-t border-[var(--border)] pt-12 md:grid-cols-2"><div><h2 className="lt-heading-2">Why include an unpaid-time buffer?</h2><p className="lt-body mt-4">Freelancers spend time on proposals, administration, learning, leave and revisions. The buffer keeps those hours from silently reducing the rate required for paid work.</p></div><div className="border border-[var(--border)] bg-[var(--surface-soft)] p-6"><h2 className="lt-heading-2">Ready to scope the work?</h2><p className="lt-body mt-3">For a website, automation, dashboard or custom business tool, share the requirement with LeTrusto.</p><Link href="/services/quote" className="lt-btn lt-btn-sm lt-btn-secondary mt-5">Get a quote</Link></div></section><DigitalProductCallout freelancer /><ServiceCallout /></main>; }
