TRUST_CLAIM_STATUSES = ("UNVERIFIED", "PENDING", "VERIFIED", "REJECTED", "EXPIRED")
TRUST_VERIFICATION_METHODS = (
    "SUPPLIER_DOCUMENT",
    "MANUFACTURER_DOCUMENT",
    "CERTIFICATION",
    "TEST_REPORT",
    "INTERNAL_REVIEW",
    "CUSTOMER_FEEDBACK",
    "SYSTEM_REVIEW",
    "OTHER",
)
TRUST_AUDIT_EVENTS = (
    "CLAIM_CREATED",
    "CLAIM_UPDATED",
    "EVIDENCE_CREATED",
    "EVIDENCE_UPDATED",
    "EVIDENCE_ATTACHED",
    "VERIFICATION_CREATED",
)
